[build]
  publish = "/"
  command = "echo 'No build command required'"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/reels-download"
  to = "/pages/reels-download.html"
  status = 200

[[redirects]]
  from = "/photos-download"
  to = "/pages/photos-download.html"
  status = 200

[[redirects]]
  from = "/stories-download"
  to = "/pages/stories-download.html"
  status = 200

[[redirects]]
  from = "/igtv-download"
  to = "/pages/igtv-download.html"
  status = 200

[[redirects]]
  from = "/carousel-download"
  to = "/pages/carousel-download.html"
  status = 200

[[redirects]]
  from = "/videos-download"
  to = "/pages/videos-download.html"
  status = 200

[[redirects]]
  from = "/audio-download"
  to = "/pages/audio-download.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/pages/privacy.html"
  status = 200

# Language specific redirects - Common languages
[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/es/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/fr/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/de/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/it/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/pt/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/ru/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/ja/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/zh-CN/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/zh-TW/*"
  to = "/index.html"
  status = 200

# Language specific redirects - More languages
[[redirects]]
  from = "/nl/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/ko/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/ar/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/hi/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/bn/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/pl/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/tr/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/vi/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/th/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/id/*"
  to = "/index.html"
  status = 200

# Language specific redirects - Even more languages
[[redirects]]
  from = "/uk/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/sv/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/no/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/fi/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/da/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/cs/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/el/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/hu/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/ro/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/sk/*"
  to = "/index.html"
  status = 200

# Fallback redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200